### ISSUE TITLE
Type check fails with `"moduleResolution": "NodeNext"`

### ISSUE THREAD

**Issue by augustjk** [parse5/parse5-tools#16]
Setting `"moduleResolution": "NodeNext"` in tsconfig causes type checking to fail as it respects package.json exports making direct imports from `parse5/dist/tree-adapters/default.js` not resolve.

`parse5` only allows importing from the module index in this mode. https://github.com/inikulin/parse5/blob/d2e403286bc9bd03d98e1af6f7f1ecfe0b8f3257/packages/parse5/package.json#L33-L37

It does export `DefaultTreeAdapterMap` (https://github.com/inikulin/parse5/blob/d2e403286bc9bd03d98e1af6f7f1ecfe0b8f3257/packages/parse5/lib/index.ts#L6) so it's possible to grab the individual types from that. Something like...
```ts
import type {DefaultTreeAdapterMap} from 'parse5';

type Element = DefaultTreeAdapterMap['element'];
```

**Comment by 43081j** [comment]
Funnily enough, while reading the sources the other day I also noticed that import and wondered if it would cause problems 😬

I think you're right and we will just have to get it from the export in the main file. I'll update it today if I can
