### ISSUE TITLE
`traverse` Visitor is visiting some nodes more than once.

### ISSUE THREAD

**Issue by cohenerickson** [parse5/parse5-tools#22]
### My use/Description
I am using the `traverse` function to modify the HTML string of webpages. I am using the `traverse` function of this package in order to iterate through all nodes of the tree but am running into some problems where the `Visitor` visits some nodes more than once, causing issues down the line. This issue is most noticeable with `<script></script>` elements. One major part of my program is modifying the JavaScript of a webpage (in this case the inline scripts) in order to emulate certain API's in a different context. I know that the issue doesn't stem from my JavaScript rewriter as it works just fine for non-inline scripts such as those referenced by `<script src="..."></script>`.

I'm not sure if this behavior is expected or not as I don't have a ton of experience with parse5 and with this package. If this behavior is expected, what can I do to fix it? Or if not, are there any temporary solutions that I could implement?

I have attempted to create my own traverse function but with the same issue. I believe it to be a side affect of how parse5 structures the AST but I could be wrong.

### Example

```js
const tree = parse5.parse(`
  <script>
    console.log(location.href);
  </script>
`);

traverse(tree, {
  node(node) {
    if (node.nodeName === "script") {
      const textNode = node.childNodes[0];

      if (textNode) {
        // The actual JS rewriter is much more complex and parses the script to an AST
        // but this is just to demonstrate the issue
        textNode.value = textNode.value.replace(/location/g, "_$location");
      }
    }
  }
})

console.log(parse5.serialize(tree));
```

Input:
```html
<script>
  console.log(location.href);
</script>
```

Output:
```html
<script>
  console.log(_$_$location.href);
</script>
```

Expected:
```html
<script>
  console.log(_$location.href);
</script>
```

**Comment by 43081j** [comment]
strangely i'm not seeing that locally with exactly your example (plus the imports)

could you let me know what version of parse5 and parse5/tools you're using?

i wonder if there's a newer version available that fixes it... if there is then we can thank felix for fixing a bug he didn't know existed! 😂

**Comment by cohenerickson** [comment]
Hmm, I didn't explicitly test just the example code I provided, just simplified my implementation and copied from there. It appears that I still had some other code for getting the value of a `<base>` tag which happened to also call the JS rewriter. Probably should have tested the example first in hindsight but I was a little frustrated as I had spent an hour trying to figure it out.

**Comment by 43081j** [comment]
no worries, was still worth you bringing it up. hope i managed to help
